owner: info-devf5r
repo: VPN
user-agent: info-devf5r

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Internet Archive
    url: https://archive.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE

# أضف إخطارات التوقف
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - AnandChowdhary

# تكوين موقع حالتك
# http://localhost:3000/docs/configuration#status-website
status-website:
  cname: info-devf5r.github.io/status-page/
  logoUrl: https://raw.githubusercontent.com/info-devf5r/status-page.js.org/master/static/img/icon.svg
  name: VPN
  introTitle: "** info-devf5r ** هي صفحة الحالة وجهاز مراقبة وقت التشغيل مفتوحة المصدر ، وهي مدعومة بالكامل بواسطة GitHub."
  introMessage: هذه عينة من صفحة الحالة تستخدم بيانات ** في الوقت الفعلي ** من [Github repository] (https://github.com/info-devf5r/status-page). لا يلزم وجود خادم - فقط إجراءات GitHub والمشكلات والصفحات. [** احصل على ما لديك مجانًا **] (https://github.com/info-devf5r/status-page)
  apiBaseUrl: https://api.github.com
  userContentBaseUrl: https://raw.githubusercontent.com
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
